/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package resume;

import com.sun.pdfview.PDFFile;
import com.sun.pdfview.PDFPage;
import com.sun.pdfview.PagePanel;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.file.DirectoryNotEmptyException;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import GUI.View;
import GUI.View;
import static GUI.View.RESULT;
import static resume.BE1.fo;
import static resume.BE1.writer;

public class ViewSample extends javax.swing.JFrame {
int z=1;
   int p;
   ByteBuffer buf;
   File file;
            RandomAccessFile raf;
            FileChannel channel;
            PDFFile pdffile;
            PDFPage page;
            
   static PagePanel panel = new PagePanel();
     static JFrame frame;
    public void view()
    {
        try {
            frame = new JFrame("Sample Resume...");
            frame.setVisible(true);
                      this.getContentPane().setBackground(new Color(0,0,0));
            Dimension expectedDimension = new Dimension(650, 650);

        panel.setPreferredSize(expectedDimension);
        panel.setMaximumSize(expectedDimension);
        panel.setMinimumSize(expectedDimension);
            Box box = new Box(BoxLayout.Y_AXIS);

        box.add(Box.createVerticalGlue());
        box.add(panel);     
        box.add(Box.createVerticalGlue());
        frame.add(box);
            frame.pack();
            frame.setLocationRelativeTo(null);
            file = new File(RESULT);
            raf = new RandomAccessFile(file, "r");
            channel = raf.getChannel();
            buf = channel.map(FileChannel.MapMode.READ_ONLY,
                    0, channel.size());
            pdffile = new PDFFile(buf);
            p= pdffile.getNumPages();
            page = pdffile.getPage(z);
            panel.showPage(page) ;
            
        }
        catch( IOException e)
        {
            
        }
    }
        public void viewV()
    {
        try {
            
            //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame = new JFrame("Sample Resume...");
            frame.setVisible(true);
                      this.getContentPane().setBackground(new Color(0,0,0));
            
            //JFrame frame = new JFrame("PDF Test");
            //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            
            Dimension expectedDimension = new Dimension(650, 650);

        panel.setPreferredSize(expectedDimension);
        panel.setMaximumSize(expectedDimension);
        panel.setMinimumSize(expectedDimension);
            Box box = new Box(BoxLayout.Y_AXIS);

        box.add(Box.createVerticalGlue());
        box.add(panel);     
        box.add(Box.createVerticalGlue());
        frame.add(box);
            frame.pack();
            frame.setLocationRelativeTo(null);
            
            
            //load a pdf from a byte buffer
            file = new File(RESULT);
            raf = new RandomAccessFile(file, "r");
            channel = raf.getChannel();
            buf = channel.map(FileChannel.MapMode.READ_ONLY,
                    0, channel.size());
            pdffile = new PDFFile(buf);
            p= pdffile.getNumPages();
            page = pdffile.getPage(z);
            panel.showPage(page) ;

        }
        catch( IOException e)
        {
            
        }
    }

    public ViewSample() {
        initComponents();
                  this.getContentPane().setBackground(new Color(0,0,0));
                     
        view();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up = new javax.swing.JButton();
        down = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Sample");

        up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pg1.png"))); // NOI18N
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });

        down.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pg2.png"))); // NOI18N
        down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/samples.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(down, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(down)
                    .addComponent(up)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
      if(z<p&&z>=0)
        {      up.setEnabled(true);
z=z+1;
frame.dispose();
if(z!=0)
viewV();  }                                       
    }//GEN-LAST:event_upActionPerformed

    private void downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downActionPerformed
        if(z> 0&&z<=p)
        {    down.setEnabled(true);
        z=z-1;
        frame.dispose();
        viewV();  
        }

    }//GEN-LAST:event_downActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        frame.dispose();
        this.dispose();
        new View().setVisible(true);
    
    }//GEN-LAST:event_backActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton down;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
